server:
  port: 9191

spring:
  application:
    name: api-gateway   
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employees/**
          filters:
            - name: CircuitBreaker
              args:
                name: employee-service
                fallbackuri  : forward:/employeeServiceFallback
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/departments/**  
          filters:
            - name: CircuitBreaker
              args:
                name: department-service
                fallbackuri  : forward:/departmentServiceFallback
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      instance:
        hostname: localhost
        
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 16000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream